- alias: Living Room Sunset Lights
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom

- alias: Fluxer Switch On By Default
  trigger: 
    platform: event
    event_type: homeassistant_start
  action: 
    service: homeassistant.turn_on
    entity_id: switch.fluxer  

- alias: Office Lights Motion (On)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.office_lights

- alias: Office Lights Motion (Off)
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
      to: 'off'
      for:
        minutes: 30
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: group.office_lights

- alias: Living Room Lights (On)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_3_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom
