- alias: Living Room Lights On At Sunset
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom_lights

- alias: Kitchen Light on at Sunset
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.kitchen

- alias: Fluxer Switch On By Default
  trigger: 
    platform: event
    event_type: homeassistant_start
  action: 
    service: homeassistant.turn_on
    entity_id: switch.fluxer  

- alias: Office Lights Motion (On)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
    to: 'on'
  condition: 
    condition: time
    after: '07:30'
    before: '23:30'
  action:
    service: homeassistant.turn_on
    entity_id: group.office_lights



- alias: Office Lights Motion (Off)
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
      to: 'off'
      for:
        minutes: 30
  action:
    - service: homeassistant.turn_off
      entity_id: group.office_lights

- alias: Living Room Lights (On)
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_3_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom_lights

- alias: New Home Assistant Version Notifier
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.simplepush
    data_template:
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

- alias: Generate Configuration Graph 
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: shell_command.generate_graph
