- alias: Turn on light when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.couchbot

- alias: Turn on office lights when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_2_0
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.officebot

- alias: Turn off lights when there is no motion
  trigger:
    platform: state
    entity_id: sensor.motion_sensor
    state: 'off'
    for:
    minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.officebot
