homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# FRONTEND HTTP PASSWORD PROTECTION SETUP
http:
  api_password: !secret http_password
  server_host: 127.0.0.1

# DATABASE SETUP USING MySQL
recorder:
  db_url: !secret db_url
  purge_days: 5
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.ram_use
      - media_player.google_play__blackbox
      - media_player.raptor
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp
      - sensor.date__time
      - sensor.date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time__date
      - sensor.date 
      - sensor.average_load_15m
      - sensor.average_load_5m 
      - sensor.worldclock_sensor
      - sensor.homeassistant_uptime
      - sensor.homeassistant_version
      - sensor.time
       
  
history:  
# Enables the frontend
###############################################################################
# Feel free to add/modify and customize the themes below to your heart's content
# Some of the themes I made, some I stole from online :) 

frontend:
  themes:
    dark_teal:
      # Main Stuff #
      primary-color: "#1DE9B6" # Primary (most of the UI)
      primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
      secondary-background-color: "#303030" # Secondary background colour (main UI background)
      paper-card-background-color: "#424242" # Card background colour
      paper-item-icon-color: "#1DE9B6" # Icon colour
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # Card header text colour
      # Nav Menu #
      paper-listbox-background-color: "#424242" # Listbox background colour
      paper-listbox-color: "#FFFFFF" # Listbox text colour
      paper-grey-200: "#616161" # Listbox selected item background colour
      # Switches #
      paper-toggle-button-checked-ink-color: "#1DE9B6"
      paper-toggle-button-checked-button-color: "#1DE9B6"
      paper-toggle-button-checked-bar-color: "#1DE9B6"
      # Sliders #
      paper-slider-knob-color: "#1DE9B6"
      paper-slider-knob-start-color: "#1DE9B6"
      paper-slider-pin-color: "#1DE9B6"
      paper-slider-active-color: "#1DE9B6"
      paper-slider-secondary-color: "#33F2D8"
    dark_orange:
      primary-color: "#ff9800"
      light-primary-color: "#ffc947"
      dark-primary-color: "#c66900"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#62717b"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--sidebar-text_-_background)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
    dark_red:
    # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b"
    # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
    dark_cyan:
    # Main colors that can be changed
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"      
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
    # Colors based on variables, see above
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
    light_beach:
      dark-primary-color: "#88d8b0"
      primary-color: "#ff6f69"
      light-primary-color: "#ffcc5c"
      paper-toggle-button-checked-ink-color: "#ff6f69"
      paper-toggle-button-checked-button-color: "#88d8b0"
      paper-toggle-button-checked-bar-color: "#ffcc5c"
      paper-slider-knob-color: "#88d8b0"
      paper-slider-knob-start-color: "#88d8b0"
      paper-slider-pin-color: "#88d8b0"
      paper-slider-active-color: "#88d8b0"
      paper-slider-secondary-color: "#ffeead"      
    light_green:
      dark-primary-color: "#009688"
      primary-color: "#009688"
      light-primary-color: "#009688"
      paper-toggle-button-checked-ink-color: "#009688"
      paper-toggle-button-checked-button-color: "#009688"
      paper-toggle-button-checked-bar-color: "#99d5cf"
      paper-slider-knob-color: "#66c0b7"
      paper-slider-knob-start-color: "#32ab9f"
      paper-slider-pin-color: "#66c0b7"
      paper-slider-active-color: "#009688"
      paper-slider-secondary-color: "#009688"
    light_pink:
      dark-primary-color: "#ff084a"
      primary-color: "#fc3468"
      light-primary-color: "#ffc2cd"
      paper-toggle-button-checked-ink-color: "#ff6289"
      paper-toggle-button-checked-button-color: "#ff084a"
      paper-toggle-button-checked-bar-color: "#ffc2cd"
      paper-slider-knob-color: "#ff084a"
      paper-slider-knob-start-color: "#ff084a"
      paper-slider-pin-color: "#ff084a"
      paper-slider-active-color: "#ff084a"
      paper-slider-secondary-color: "#ff93ac"









# Enables the HASS Updater
updater:
  include_used_components: true
# Enables frontend configuration assistance
config:
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
# Make a fake Hue for Alexa
emulated_hue:
  expose_by_default: true

logger: 


tts: 
  - platform: google

octoprint:
  host: 192.168.1.111
  api_key: !secret octoprint 

digital_ocean:
  access_token: !secret digitaloceantoken


notify:
  - name: simplepush
    platform: simplepush
    device_key: !secret simplepushkey

#google:
  #client_id: !secret googleclientid
  #client_secret: !secret googleclientsecret




############################################
# LIGHT
############################################
light:
  - platform: lifx
    broadcast: 192.168.1.255

scene:
  platform: lifx_cloud
  token: !secret lifxapitoken
############################################
# MEDIA PLAYERS
############################################

# Google Play Music - Brian Desktop
media_player 2:
  platform: gpmdp
  host: 192.168.1.114
  name: Google Play - Blackbox

media_player 3:
  platform: cast
  
# Track the sun
sun:

usps:
  username: !secret usps_username
  password: !secret usps_password
  name: 'USPS'

camera:
  - platform: usps
    scan_interval: 5
################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/zwave
  autoheal: false
  #config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  
############################################
# Device Tracker
############################################
device_tracker:
  - platform: owntracks
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no
#########################################
# MQTT
##########################################
mqtt:
  broker: !secret mqttbroker
  port: 19742
  username: !secret mqttuser
  password: !secret mqttpassword
############################################
# Panels
############################################
# These are broken due to HTTP loading on HTTPS connection.
panel_iframe:
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://192.168.1.1'
  modem:
    title: 'Modem Admin'
    icon: mdi:router-wireless
    url: 'http://192.168.100.1'
  graph:
    title: Graph
    icon: mdi:vector-polyline
    url: "https://raptorbot.ddns.net/local/graph.html"
############################################       
# Includes
############################################
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
script: !include_dir_named script/
binary_sensor: !include_dir_merge_list binary_sensor 
shell_command: !include_dir_named shell_command/
group: !include groups.yaml
input_select: !include_dir_merge_named input_select

