homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# Enables Auth Component 
auth: 

# FRONTEND HTTP PASSWORD PROTECTION SETUP
http:
  api_password: !secret http_password
  server_host: 127.0.0.1
  use_x_forwarded_for: True
  trusted_proxies: 
    - 127.0.0.1
    - ::1

# DATABASE SETUP USING MySQL
recorder:
  db_url: !secret db_url
  purge_interval: 2
  purge_keep_days: 3
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.ram_use
      - media_player.google_play__blackbox
      - media_player.raptor
      - sensor.date__time
      - sensor.date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time__date
      - sensor.date 
      - sensor.average_load_15m
      - sensor.average_load_5m 
      - sensor.worldclock_sensor
      - sensor.homeassistant_uptime
      - sensor.homeassistant_version
      - sensor.time
      - sensor.home_to_kinna_work
      - sensor.kinna_work_to_home
      - sensor.lyft_home_to_kinna_work
      - sensor.lyft_price
      - sensor.lyft_time

no_ip:
  domain: !secret noip
  username: !secret noipusername
  password: !secret noippassword     
  
history:  

frontend:
  themes: !include themes.yaml

# Enable Map
map: 
  
# Enables the HASS Updater
updater:
  include_used_components: true
# Enables frontend configuration assistance
config:
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
  exclude: 
    entities:
      - sensor.brianjkinghomeassistantconfig_last_build_duration
      - sensor.brianjkinghomeassistantconfig_last_build_id
      - sensor.brianjkinghomeassistantconfig_last_build_state
      - sensor.brianjkinghomeassistantconfig_state
      - switch.eebrianjkingcom
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant


# Make a fake Hue for Alexa
emulated_hue:
  expose_by_default: true

# Set Logging Levels

logger: 
  default: info
  logs:
    homeassistant.core: error
    homeassistant.components.automation: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.discovery: warn
    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
    homeassistant.components.recorder: error
    homeassistant.components.zwave: debug
    homeassistant.helpers.script: info
    homeassistant.helpers.entity: critical
    homeassistant.exceptions: info
    py.warnings: error
    root: warn
    homeassistant.components.switch.flux: info

tts: 
  - platform: google

#octoprint:
#  host: 192.168.1.111
#  api_key: !secret octoprint 

digital_ocean:
  access_token: !secret digitaloceantoken

# Setup push notifications using the Simplepush service
notify:
  - name: simplepush
    platform: simplepush
    device_key: !secret simplepushkey

#google:
  #client_id: !secret googleclientid
  #client_secret: !secret googleclientsecret

############################################
# LIGHT
############################################
light:
  - platform: lifx
   

scene:
  platform: lifx_cloud
  token: !secret lifxapitoken
############################################
# MEDIA PLAYERS
############################################

# Google Play Music - Brian Desktop
media_player 2:
  platform: gpmdp
  host: 192.168.1.110
  name: Google Play - Blackbox

media_player 3:
  platform: cast
  
# Track the sun
sun:

#usps:
#  username: !secret usps_username
#  password: !secret usps_password
 # driver: phantomjs
#  name: 'USPS'

#camera:
 # - platform: usps
 #   scan_interval: 5
#  - platform: mjpeg
#    mjpeg_url: https://192.168.1.107:8000/video
################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/zwave
  autoheal: false
  #config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  
############################################
# Device Tracker
############################################
device_tracker:
  #- platform: owntracks
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no
#########################################
# MQTT
##########################################
# Temporarily disabled.
#mqtt:
  #broker: !secret mqttbroker
  #port: 19742
  #username: !secret mqttuser
  #password: !secret mqttpassword

############################################
# Weblink
############################################
weblink:
  entities:
    - name: Router Admin
      icon: mdi:router-wireless
      url: http://192.168.1.1
    - name: Modem Admin
      icon: mdi:router-wireless
      url: http://10.0.0.1

############################################       
# Includes
############################################
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
script: !include_dir_named script/
binary_sensor: !include_dir_merge_list binary_sensor 
shell_command: !include_dir_named shell_command/
group: !include groups.yaml
input_select: !include_dir_merge_named input_select
