homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# FRONTEND HTTP PASSWORD PROTECTION SETUP
http:
  api_password: !secret http_password
  server_host: 127.0.0.1

# DATABASE SETUP USING MySQL
recorder:
  db_url: !secret db_url
  purge_days: 5
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.ram_use
      - media_player.google_play__blackbox
      - media_player.raptor
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp
      - sensor.date__time
      - sensor.date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time__date
      - sensor.date 
      - sensor.average_load_15m
      - sensor.average_load_5m 
      - sensor.worldclock_sensor
      - sensor.homeassistant_uptime
      - sensor.homeassistant_version
      - sensor.time
       
  
history:  
# Enables the frontend
frontend:
  themes:
    minimal:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    stormy_hues:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    vintage:
      dark-primary-color: "#373f27"
      primary-color: "#636b46"
      light-primary-color: "#e9e7da"
      paper-toggle-button-checked-ink-color: "#cda34f"
      paper-toggle-button-checked-button-color: "#cda34f"
      paper-toggle-button-checked-bar-color: "#cda34f"
      paper-slider-knob-color: "#cda34f"
      paper-slider-knob-start-color: "#cda34f"
      paper-slider-pin-color: "#cda34f"
      paper-slider-active-color: "#cda34f"
    done1:
      dark-primary-color: "#565656"
      primary-color: "#C09F80"
      light-primary-color: "#D7CEC7"
      paper-toggle-button-checked-ink-color: "#76323F"
      paper-toggle-button-checked-button-color: "#76323F"
      paper-toggle-button-checked-bar-color: "#76323F"
      paper-slider-knob-color: "#76323F"
      paper-slider-knob-start-color: "#76323F"
      paper-slider-pin-color: "#76323F"
      paper-slider-active-color: "#76323F"
      paper-slider-secondary-color: "#FFE0B2"

# Enables the HASS Updater
updater:
  include_used_components: true
# Enables frontend configuration assistance
config:
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
# Make a fake Hue for Alexa
emulated_hue:
  expose_by_default: true

logger: 


tts: 
  - platform: google

octoprint:
  host: 192.168.1.111
  api_key: !secret octoprint 

digital_ocean:
  access_token: !secret digitaloceantoken


notify:
  - name: simplepush
    platform: simplepush
    device_key: !secret simplepushkey

#google:
  #client_id: !secret googleclientid
  #client_secret: !secret googleclientsecret




############################################
# LIGHT
############################################
light:
  - platform: lifx
    broadcast: 192.168.1.255

scene:
  platform: lifx_cloud
  token: !secret lifxapitoken
############################################
# MEDIA PLAYERS
############################################

# Google Play Music - Brian Desktop
media_player 2:
  platform: gpmdp
  host: 192.168.1.114
  name: Google Play - Blackbox

media_player 3:
  platform: cast
  
# Track the sun
sun:

usps:
  username: !secret usps_username
  password: !secret usps_password
  name: 'USPS'

camera:
  - platform: usps
    scan_interval: 5
################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/zwave
  autoheal: false
  #config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  
############################################
# Device Tracker
############################################
device_tracker:
  - platform: owntracks
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no
#########################################
# MQTT
##########################################
mqtt:
  broker: !secret mqttbroker
  port: 19742
  username: !secret mqttuser
  password: !secret mqttpassword
############################################
# Panels
############################################
# These are broken due to HTTP loading on HTTPS connection.
panel_iframe:
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://192.168.1.1'
  modem:
    title: 'Modem Admin'
    icon: mdi:router-wireless
    url: 'http://192.168.100.1'
  graph:
    title: Graph
    icon: mdi:vector-polyline
    url: "https://raptorbot.ddns.net/local/graph.html"
############################################       
# Includes
############################################
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
script: !include_dir_named script/
binary_sensor: !include_dir_merge_list binary_sensor 
shell_command: !include_dir_named shell_command/
group: !include groups.yaml
input_select: !include_dir_merge_named input_select

