homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password



# Enables Auth Component 
auth: 

# FRONTEND HTTP PASSWORD PROTECTION SETUP
http:
  server_host: 127.0.0.1
  use_x_forwarded_for: True
  base_url: !secret fakehost
  trusted_proxies: 
    - 127.0.0.1
    - ::1
  #trusted_networks:
   # - 127.0.0.1
   # - ::1
   # - 192.168.1.0/24

# DATABASE SETUP USING MySQL
recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 10
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.ram_use
      - media_player.raptor
      - sensor.date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.date 
      - sensor.average_load_15m
      - sensor.average_load_5m 
      - sensor.worldclock_sensor
      - sensor.homeassistant_uptime
      - sensor.homeassistant_version
      - sensor.time
      - sensor.home_to_kinna_work
      - sensor.kinna_work_to_home
      - sensor.lyft_home_to_kinna_work
      - sensor.lyft_price
      - sensor.lyft_time
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.pihole_queries_cached
      - sensor.weather_ozone
      - sensor.brianjkinghomeassistantconfig_state
      - sensor.brianjkinghomeassistantconfig_last_build_state
      - sensor.brianjkinghomeassistantconfig_last_build_started_at
      - sensor.brianjkinghomeassistantconfig_last_build_id
      - sensor.brianjkinghomeassistantconfig_last_build_finished_at
      - sensor.brianjkinghomeassistantconfig_last_build_duration
      - binary_sensor.1up_brianjkingme
      - binary_sensor.1upkeyboardscom
      - binary_sensor.brianjkingcom
      - binary_sensor.brianjkingio 
      - binary_sensor.eebrianjkingcom_ip
      - binary_sensor.hass 
      - binary_sensor.robotberame
      - sensor.load_5m
      - sensor.load_15m
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.allergy_index_forecasted_average_2
      - sensor.allergy_index_historical_average_2
      - sensor.allergy_index_today
      - sensor.allergy_index_tomorrow
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant
      - sensor.brianjkinghomeassistantconfig_state
      - sensor.brianjkinghomeassistantconfig_last_build_state
      - sensor.brianjkinghomeassistantconfig_last_build_started_at
      - sensor.brianjkinghomeassistantconfig_last_build_id
      - sensor.brianjkinghomeassistantconfig_last_build_finished_at
      - sensor.brianjkinghomeassistantconfig_last_build_duration


no_ip:
  domain: !secret noip
  username: !secret noipusername
  password: !secret noippassword
  timeout: 60     
  
history:  

frontend:
  themes: !include themes.yaml

# Enable Map
map: 
  
# Enables the HASS Updater
updater:
  include_used_components: true
# Enables frontend configuration assistance
config:
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
  exclude: 
    entities:
      - sensor.brianjkinghomeassistantconfig_last_build_duration
      - sensor.brianjkinghomeassistantconfig_last_build_id
      - sensor.brianjkinghomeassistantconfig_last_build_state
      - sensor.brianjkinghomeassistantconfig_state
      - switch.eebrianjkingcom
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant


# Make a fake Hue for Alexa
emulated_hue:
  expose_by_default: true

# Set Logging Levels

logger: 
  default: info
  logs:
    homeassistant.core: error
    homeassistant.components.automation: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.discovery: warn
    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
    homeassistant.components.recorder: error
    homeassistant.components.zwave: warn
    homeassistant.helpers.script: info
    homeassistant.helpers.entity: critical
    homeassistant.exceptions: info
    homeassistant.components.switch.flux: debug
    homeassistant.components.light.lifx: debug
    homeassistant.components.mqtt: debug
    homeassistant.components.scene.lifx_cloud: debug
    py.warnings: error
    root: warn

# People Tracking 0.88
person: 


tts: 
  - platform: google_translate
    language: 'en'

digital_ocean:
  access_token: !secret digitaloceantoken

# Setup push notifications using the Simplepush service
notify:
  - name: simplepush
    platform: simplepush
    device_key: !secret simplepushkey

# Speedtest
speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload


#google:
  #client_id: !secret googleclientid
  #client_secret: !secret googleclientsecret

############################################
# LIGHT
############################################

light:
  - platform: switch
    name: Tribot
    entity_id: switch.tribot
  - platform: switch
    name: Christmas Tree 
    entity_id: switch.christmas_tree
   

scene:
  platform: lifx_cloud
  token: !secret lifxapitoken
############################################
# MEDIA PLAYERS
############################################

media_player 4:
  platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret


  
# Track the sun
sun:

#usps:
#  username: !secret usps_username
#  password: !secret usps_password
 # driver: phantomjs
#  name: 'USPS'

#camera:
 # - platform: usps
 #   scan_interval: 5
 #  - platform: mjpeg
 #    mjpeg_url: https://192.168.1.107:8000/video

#camera:
 # - platform: generic
  #  name: USPS Mail Pictures
  #  still_image_url: !secret still_image_url
#  - platform: mjpeg
#    mjpeg_url: http://192.168.1.133:8000/video
################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/zwave
  autoheal: false
  #config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  
############################################
# Device Trackers
############################################
device_tracker:
  - platform: tile
    username: !secret tilelogin
    password: !secret tilepass
    show_inactive: true
    monitored_variables:
      - TILE
  #- platform: bluetooth_le_tracker
   # device_id: hci0
   # track_new_devices: True

  #- platform: nmap_tracker
    #hosts: 
     # - 192.168.1.104
      #- 192.168.1.105
    #home_interval: 25
    #new_device_defaults:
      #track_new_devices: True
  
system_health: 
 

#########################################
# WAKE ON LAN SUPPORT - TESTING
##########################################
wake_on_lan:
  broadcast_address: "255.255.255.0"
    
#########################################
# MQTT
##########################################
#mqtt:
#  broker: !secret mqttbroker
#  port: 1883
#  username: !secret mqttuser
#  password: !secret mqttpassword

#########################################
# API
##########################################

#api:
#websocket_api: 

############################################
# Weblink
############################################
weblink:
  entities:
    - name: Router Admin
      icon: mdi:router-wireless
      url: http://192.168.1.1
    - name: Modem Admin
      icon: mdi:router-wireless
      url: http://192.168.0.1

############################################       
# Includes
############################################
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
script: !include_dir_named script/
binary_sensor: !include_dir_merge_list binary_sensor 
shell_command: !include_dir_named shell_command/
group: !include groups.yaml
input_select: !include_dir_merge_named input_select
zone: !include zone.yaml
