homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  server_host: 127.0.0.1

recorder:
  db_url: !secret db_url
  purge_days: 7
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_precip_intensity
      - sensor.weather_precip_probability
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sun.sun 
  
history:  
# Enables the frontend
frontend:
updater:
config:
# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

emulated_hue:
  expose_by_default: true

tts: 
  - platform: google

octoprint:
  host: 192.168.1.111
  api_key: !secret octoprint 

logger:
  default: error
  #logs:
    #homeassistant.components.light.lifx: debug
    #homeassistant.components.switch.flux: info                     
###########################
# VIEWS
###########################

group:
  default_view:
    view: yes
    entities:
      - group.all_lights
      - media_player.raptor
      - group.system
      - group.weather
      - group.internet
      - media_player.google_play__blackbox
      - group.all_automations
      - switch.wake_on_lan
  living_room:
    name: Living Room
    view: yes 
    entities: 
      - group.livingroom_lights
      - media_player.raptor
  office:
    name: Office
    view: yes
    entities:
      - light.officebotfloor
      - light.officebot
      - group.internet
      - group.weather
      - group.ship
      - media_player.google_play__blackbox
      - group.all_devices
      - switch.wake_on_lan
      - switch.fluxer
  bedroom:
    name: Bedroom
    view: yes
    entities:
      - light.sleepbot
      - group.weather
  kitchen: 
    name: Kitchen
    view: yes
    entities: 
      - light.kitchen     
  printer:
    name: 3D
    view: yes
    entities: 
      - group.3d_print

  
###########################
# GROUPS
###########################    
  Internet: sensor.speedtest_download, sensor.speedtest_upload, sensor.speedtest_ping
  Weather: sensor.weather_apparent_temperature, sensor.weather_humidity, sensor.weather_icon, sensor.weather_precip_intensity, sensor.weather_precip_probability, sensor.weather_summary, sensor.weather_temperature, sensor.weather_hourly_summary, sensor.weather_daily_summary, sensor.weather_wind_speed, sun.sun
  System: sensor.cpu_use, sensor.ram_free, sensor.ram_use
  Ship: sensor.packages
  livingroom_lights: light.tribot, light.couchbot 
  office_lights: light.officebot, light.officebotfloor
  3D_print: sensor.octoprint_actual_bed_temp, sensor.octoprint_actual_tool0_temp, sensor.octoprint_current_state, sensor.octoprint_job_percentage, sensor.octoprint_target_bed_temp, sensor.octoprint_target_tool0_temp
################################################################          
# Inputs
################################################################

switch:
  platform: flux
  lights:
    - light.officebot
    - light.officebotfloor
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:59'
  start_colortemp: 3200
  sunset_colortemp: 2600
  stop_colortemp: 2500
  disable_brightness_adjust: True 
  mode: mired
  
switch 2:
  - platform: wake_on_lan
    mac_address: "D8:CB:8A:E2:03:A2"
    name: "blackbox"
    host: 192.168.1.114

#switch 3:
#  - platform: tplink
#    host: 192.168.1.116
################################################################          
# Sensors/Components
################################################################

# Lifx
light:
  - platform: lifx
    broadcast: 192.168.1.255
  
# Google Play Music - Brian Desktop
media_player 2:
  platform: gpmdp
  host: 192.168.1.114
  name: Google Play - Blackbox

media_player 3:
  platform: cast
  
# Track the sun
sun:

sensor:
  - platform: darksky
    name: Weather
    api_key: !secret skydark 
    monitored_conditions:
      - apparent_temperature
      - temperature
      - humidity
      - icon
      - precip_intensity
      - precip_probability
      - summary
      - wind_speed
      - hourly_summary
      - daily_summary
    update_interval: '00:30'

sensor 2:
  - platform: speedtest
    name: Internet
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 15
      - 30
      - 45
      
sensor 3:
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use

sensor 4:
  - platform: usps
    username: !secret usps_username
    password: !secret usps_password
    name: packages
    
sensor 5:
  - platform: uber
    server_token: !secret uber_token
    start_latitude: !secret latitude 
    start_longitude: !secret longitude


sensor 6:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage 

################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/ttyACM0


###############################
# Device Tracker
###############################

device_tracker:
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no

################################################################
# Panels
################################################################
# These are broken due to HTTP loading on HTTPS connection.
panel_iframe:
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://192.168.1.1'
  modem:
    title: 'Modem Admin'
    icon: mdi:router-wireless
    url: 'http://192.168.100.1'

################################################################          
# Automation
################################################################
automation: !include automation.yaml
