- platform: template
  sensors:
    front_door_status:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_4_0", "off") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_4_0", "off") %}mdi:logout{% else %}mdi:window-open{% endif %}'
