- platform: template
  sensors:
      front_door_status:
        value_template: '{% if states.binary_sensor.ecolink_doorwindow_sensor_sensor_4_0 %}
          {% if states.binary_sensor.ecolink_doorwindow_sensor_sensor_4_0 == "on" %}
            Open
          {% else %}
            Closed
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Front Door'
