- platform: google_travel_time
  name: Home to Kinna Work
  api_key: !secret gmaps
  origin: !secret homelocation
  destination: !secret kwork
  options:
    mode: transit

- platform: google_travel_time
  name: Kinna Work to Home 
  api_key: !secret gmaps
  origin: !secret kwork
  destination: !secret homelocation 
  options:
    mode: transit
