###############################################################
## * Special HASS related sensors - Thanks @torn8o & @CCOSTAN
###############################################################
# Disabling as command is failing repeatedly on Hassbian, not sure why.
#- platform: command_line
#  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
#  name: Current Home Assistant Version

- platform: command_line
  name: HomeAssistant Version
  command: >-
      cat /home/homeassistant/.homeassistant/.HA_VERSION
  scan_interval: 86400

- platform: uptime
  name: "HomeAssistant Uptime"
