- platform: lyft
  client_id: !secret lyftclientid
  client_secret: !secret lyftclientsecret
  start_latitude: !secret lyftstartlatitude
  start_longitude: !secret lyftstartlongitude
  end_latitude: !secret endlatitudelyft
  end_longitude: !secret endlongitudelyft
  product_ids:
    - 'lyft'

- platform: template
  sensors:
    lyft_home_to_kinna_work:
      friendly_name: "Home to Kinna's Work"
      value_template: '{{ states.sensor.lyft_price.state }} USD,  available in {{ (states.sensor.lyft_price.attributes["Pickup time estimate (in seconds)"] | int)/60 }} minutes, estimated duration {{ (states.sensor.lyft_price.attributes["Trip duration (in seconds)"] | int )/60 |round(2)}} minutes.'

