- platform: rest
  name: pollen
  resource: !secret weather_pollen_url
  value_template: "{{value_json.Location.periods[1].Index}}"
  scan_interval: 21600
  headers:
    Referer: "https://www.pollen.com"

- platform: rest
  name: cold_flu
  resource: !secret weather_cold_flu_url
  value_template: "{{value_json.Location.periods[0].Index}}"
  scan_interval: 21600
  headers:
    Referer: "https://www.pollen.com"      
