- platform: pollen
  zip_code: "60640"
  monitored_conditions: 
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - disease_average_forecasted 
