- platform: rest
  name: pollen
  resource: https://www.pollen.com/api/forecast/current/pollen/60640
  value_template: "{{value_json.Location.periods[1].Index}}"
  scan_interval: 21600
  headers:
    Referer: "https://www.pollen.com"

- platform: rest
  name: cold_flu
  resource: https://www.pollen.com/api/forecast/extended/cold/60640
  value_template: "{{value_json.Location.periods[0].Index}}"
  scan_interval: 21600
  headers:
    Referer: "https://www.pollen.com"      
