- platform: mqtt
  name: 'USPS Mail'
  state_topic: '/usps/mails'
  value_template: "{{ value }}"

- platform: mqtt
  name: USPS Packages
  state_topic: '/usps/packages'
  value_template: "{{ value }}"

  camera:
- platform: generic
  name: USPS Mail Pictures
  still_image_url: 'http://192.168.1.100:8123/www/todays_mails.gif'
