- platform: template
  sensors:
    office_motion_battery:
      friendly_name: 'Office Motion Sensor Battery'
      value_template: '{{ states.zwave.ecolink_pir_motion_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'

- platform: template
  sensors:
    front_door_sensor_battery:
      friendly_name: 'Front Door Sensor Battery'
      value_template: '{{ states.zwave.ecolink_doorwindow_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'

- platform: template
  sensors:
    livingroom_sensor_battery:
      friendly_name: 'Living Room Sensor'
      value_template: '{{ states.zwave.ecolink_unknown_type0004_id0001.attributes.battery_level }}'
      unit_of_measurement: '%'
