- alias: SimplePush Package Delivery 
  trigger:
      platform: state
      entity_id: sensor.deliveries_today
  condition:
      - condition: template
        value_template: '{{trigger.to_state.state|int > trigger.from_state.state|int}}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
  action:
      - service: notify.simplepush
        data_template:
          message: "A package was just delivered."
