- alias: Front Door Open Notification
  trigger:
  platform: state
  entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_4_0
  state: 'on'
  for:
    seconds: 15
  action:
  - service: notify.simplepush
    data_template:
      message: 'Front door is open!'
