- alias: Front Door Entryway Light
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.entrybot

- alias: Front Door Entryway WatchDog
  initial_state: True
  trigger:
    - platform: state
      entity_id:
        - light.entrybot
      to: 'on'
      for:
        minutes: 3
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"


