- alias: Front Door Open Notification
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
    state: 'on'
    for:
      seconds: 25
  action:
  - service: notify.simplepush
    data_template:
      message: 'Front door is open!'
