- alias: Front Door Entryway Light
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_4_0
    to: 'on'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_on
    entity_id: light.entrybot


