- alias: Home Assistant Startup
  hide_entity: True
  initial_state: True
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.simplepush
    data:
      title: "HomeAssistant Startup"
      message: "Home Assistant has started."
