- alias: Kitchen Light on at Sunset
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.kitchen

- alias: Kitchen Off at Midnight
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '23:59'
  action: 
    service: homeassistant.turn_off
    entity_id: light.kitchen
