- alias: Office Lights Motion (On)
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor
    to: 'on'
  condition: 
    condition: time
    after: '07:30'
    before: '23:30'
  action:
    service: homeassistant.turn_on
    entity_id: group.office_lights
    data: 
      transition: 15


- alias: Office Lights Motion (Off)
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor
      to: 'off'
      for:
        minutes: 15
  action:
    - service: homeassistant.turn_off
      entity_id: group.office_lights
      data: 
        transition: 160
