- alias: Rainy Day
  trigger:
    platform: state
    entity_id: sensor.weather_precip_intensity
    to: 'rain'
  condition:
    - condition: state
      entity_id: group.all_devices
      to: 'home'
    - condition: time
      after: '14:00'
      before: '23:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.livingroom_lights

- alias: Rain is over
  trigger:
    - platform: state
      entity_id: sensor.weather_precip_intensity
      to: 'None'
  condition:
    - condition: sun
      after: 'sunset'
  action:
    service: homeassistant.turn_off
    entity_id: group.livingroom_lights 
