###################################
# Theme Selection Automation
###################################

- alias: Theme Selection
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.theme_select
  action:
    service: frontend.theme
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"
